# Generated by Django 6.0.6 on 2026-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('completed', 'Completed'), ('wishlist', 'Wishlist'), ('dropped', 'Dropped')], default='playing', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
